import "../../../App.css";

function SettingPage(){
    return(
        <div>
            SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE<br/>SETTING PAGE
        </div>
    );
}

export default SettingPage;